[tool.poetry]
name = "ferreinox-bot"
version = "0.1.0"
description = "WhatsApp Bot for Ferreinox"
authors = ["Diego Mao"]
readme = "README.md"
package-mode = false

[tool.poetry.dependencies]
python = ">=3.11,<3.12"
flask = "*"
gunicorn = "*"
requests = "*"

# --- Â¡ESTAS SON LAS NUEVAS BIBLIOTECAS! ---
google-cloud-aiplatform = "*"
google-auth = "*"
# Ya no usamos google-generativeai

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
