# FORZAMOS A POETRY A USAR EL ÃNDICE OFICIAL DE PyPI
[[tool.poetry.source]]
name = "PyPI"
url = "https://pypi.org/simple/"
priority = "default"

[tool.poetry]
name = "ferreinox-bot"
version = "0.1.0"
description = "WhatsApp Bot for Ferreinox"
authors = ["Diego Mao"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.11,<3.12"
flask = "*"
gunicorn = "*"
google-generativeai = ">=1.0.0"
requests = "*"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
